resources:
  - ../../base

nameSuffix: -deployment1

patches:
- target:
    kind: Deployment
    name: deploy
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shared-deployment
    spec:
      replicas: 2